variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
stages:
  - build_npm
  - build_docker
services:
  - docker:dind
build_docker:
  image: docker:stable
  stage: build_docker
  before_script:
  - docker info
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - docker build -t vertig0ne/mediabutler-api:latest .
    - docker build -t vertig0ne/mediabutler-api:1.0.${CI_PIPELINE_ID}
    - docker push vertig0ne/mediabutler-api:latest
    - docker push vertig0ne/mediabutler-api:1.0.${CI_PIPELINE_ID}
build_npm:
  image: node:4.2.2
  stage: build_npm
  script:
    - npm install
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run ci-publish || true
