variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
stages:
  - build
  - test
  - deploy
services:
  - docker:dind
build_docker:
  image: docker:stable
  stage: build
  before_script:
  - docker info
  script:
    - docker build -t mediabutler/server:latest .
build_npm:
  image: node:4.2.2
  stage: build
  script:
    - npm install
test_docker:
  stage: test
  script:
    - echo "Should have tested Docker"
test_npm:
  image: node:4.2.2
  stage: test
  script:
    - echo "Should have run npm test"
deploy_npm:
  stage: deploy
  image: node:4.2.2
  script:
    - npm install
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm run ci-publish || true
deploy_docker:
  stage: deploy
  before_script:
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - docker build -t mediabutler/server:latest .
    - docker push mediabutler/server:latest