variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
stages:
  - build_npm
  - build_docker
services:
  - docker:dind
build_docker:
  image: docker:stable
  stage: build_docker
  before_script:
  - docker info
  script:
    - docker build -t vertig0ne/mediabutler-api:latest .
build_npm:
  image: node:4.2.2
  stage: build_npm
  script:
    - npm install
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
