---
version: '2'
networks:
  mediabutler:
    driver: bridge
services:
    mediabutler-api:
        build: .
        container_name: "mediabutler-api"
        image: mediabutler-api:latest
        hostname: mediabutler-api
        environment:
            - PLEX_MACHINE_ID=9f67762e320e456bb26a2dfdd1a9cb1ced19aa31
            - DB_URL=mongodb://root:passwordHere@mongodb:21017
        volumes:
            - ${HOME}/docker/mediabutler:/config:rw
        networks:
            - mediabutler
        ports:
            - 9876:9876
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        hostname: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=passwordHere
        volumes:
          - ${HOME}/docker/mediabutler/db:/data/db
        networks:
          - mediabutler
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
