---
version: '2'
networks:
  mediabutler:
    driver: bridge
services:
    mediabutler-api:
        build: .
        container_name: "mediabutler-api"
        image: mediabutler-api:latest
        hostname: mediabutler-api
        environment:
            - PLEX_MACHINE_ID=alkdhajshdjasdasdadadsd
            - DB_URL=mongodb://mongodb:21017
        volumes:
            - /Users/${USER}/docker/mediabutler:/config:rw
        networks:
            - mediabutler
        ports:
            - 9876:9876
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        hostname: mongodb
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - /Users/${USER}/docker/mediabutler/db:/data/db
        networks:
          - mediabutler
        command: mongod --smallfiles --logpath=/dev/null # --quiet
