---
version: '2'
networks:
  mb:
    driver: bridge
services:
    mediabutler-api:
        build: .
        container_name: "mediabutler-api"
        image: mediabutler-api:latest
        hostname: mediabutler-api
        environment:
            - PLEX_MACHINE_ID=9f67762e320e456bb26a2dfdd1a9cb1ced19aa31
            - DB_URL=mongodb://mongo:27017/mediabutler
        volumes:
            - ${HOME}/docker/mediabutler:/config:rw
        networks:
            - mb
        ports:
            - 9876:9876
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: "mongo"
        hostname: mongo
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGO_URL=mongodb://mongo:27017/
        volumes:
          - ${HOME}/docker/mediabutler/db:/data/db:rw
        networks:
          - mb
        command: mongod --smallfiles --bind_ip_all
